### ISSUE TITLE
Running demo

### ISSUE THREAD

**Issue by hgingras** [RitataLU/MethylC-analyzer#4]
Hello, I am trying to run the demo. I tried many combinations but didn't find the right order for the arguments.

Here is what I do:

python MethylC.py samples_list samples_list.txt input_gtf_file TAR10_2_demo.gtf path_to_files /home/helene/projects/def-helene/helene/Tickets/0194426/MethylC-analyzer/Demo -a MT -b WT -d 4 -r 200 -q 2 -bs 200000 -pvalue 0.1

I get this error: 
MethylC.py: error: unrecognized arguments: path_to_files /home/helene/projects/def-helene/helene/Tickets/0194426/MethylC-analyzer/Demo

From help menu we have:

usage: MethylC.py [-h] [-a GROUP1] [-b GROUP2] [-d DEPTH] [-r REGION] [-q QUALIFIED] [-context CONTEXT] [-hc HEATMAP_CUTOFF] [-dmrc DMR_CUTOFF] [-test TESTMETHOD] [-pvalue PVALUE]
                  [-bs BIN_SIZE] [-p PROMOTER_SIZE]
                  command samples_list input_gtf_file path_to_files

How do I integrate everything so it works.

Thanks for your help.

Helene

**Comment by beritlin** [comment]
Hello Hélène,

thank you for using the tool!
in your case, there is no need to add terms in front of the data name. 
please try this:
```
python MethylC.py all samples_list.txt TAR10_2_demo.gtf /home/helene/projects/def-helene/helene/Tickets/0194426/MethylC-analyzer/Demo -a MT -b WT -d 4 -r 200 -q 2 -bs 200000 -pvalue 0.1
```

Pei-Yu

**Comment by konetom** [comment]
Please, emphasize the keyword `'all'` in the documentation and how to use it correctly. Before I added the keyword `'all'` the same way you did in this thread, I wasn't able to run the demo as well as Helene.

**Comment by desmodus1984** [comment]
Hi,
I installed MethylC and I tried the code as you updated it. And I got several errors.
I downloaded the Demo and copied all the files to the scripts directory

/home/juaguila/MethylC-analyzer/scripts

Then, I tried running the code:
`python MethylC.py all samples_list.txt TAR10_2_demo.gtf /home/juaguila/MethylC-analyzer/scripts -a MT -b WT -d 4 -r 200 -q 2 -bs 200000 -pvalue 0.1
`
and it failed:

Traceback (most recent call last):
  File "/home/juaguila/MethylC-analyzer/scripts/MethylC.py", line 349, in <module>
    samples = pd.read_csv(samples_list,header=None,sep="\t")
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/juaguila/MethylC-analyzer/scriptssamples_list.txt'

**Then, I tried again but with the / at the end of the path.**

`python MethylC.py all samples_list.txt TAR10_2_demo.gtf /home/juaguila/MethylC-analyzer/scripts/ -a MT -b WT -d 4 -r 200 -q 2 -bs 200000 -pvalue 0.1
`

And this it worked fine for a while...

Now processing MT1s.CGmap.gz
Now processing MT2s.CGmap.gz
Now processing WT1s.CGmap.gz
Now processing WT2s.CGmap.gz
no display found. Using non-interactive Agg backend
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

but then it failed again:

*------------------------*
|generating Heatmap $ PCA|
*------------------------*
Fatal error: cannot open file '/MethylC-analyzer/scripts/heatmap_PCA_all.R': No such file or directory
*---------------*
|Identifying DMR|
*---------------*
/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/scipy/stats/_axis_nan_policy.py:394: RuntimeWarning: ks_2samp: Exact calculation unsuccessful. Switching to method=asymp.
  return hypotest_fun_in(*args, **kwds)
python: can't open file '/MethylC-analyzer/scripts/extract_transcript_regions.py': [Errno 2] No such file or directory
cat: /home/juaguila/MethylC-analyzer/scripts/TAR10_2_demo.gtf_exons.bed: No such file or directory
cat: /home/juaguila/MethylC-analyzer/scripts/TAR10_2_demo.gtf_introns.bed: No such file or directory
cat: /home/juaguila/MethylC-analyzer/scripts/TAR10_2_demo.gtf_5utr.bed: No such file or directory
cat: /home/juaguila/MethylC-analyzer/scripts/TAR10_2_demo.gtf_cds.bed: No such file or directory
cat: /home/juaguila/MethylC-analyzer/scripts/TAR10_2_demo.gtf_3utr.bed: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*3utr.bed’: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*5utr.bed’: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*_cds.bed’: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*_exons.bed’: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*_introns.bed’: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*_coding*.bed’: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*noncoding*.bed’: No such file or directory
rm: cannot remove ‘/home/juaguila/MethylC-analyzer/scripts/*5utr_start.bed’: No such file or directory

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.

-----------

*--------------------------*
|Generating ChrView figures|
*--------------------------*
Fatal error: cannot open file '/MethylC-analyzer/scripts/chrView.R': No such file or directory
Fatal error: cannot open file '/MethylC-analyzer/scripts/chrView_delta.R': No such file or directory
*--------------------*
|Generating metaplots|
*--------------------*
Fatal error: cannot open file '/MethylC-analyzer/scripts/metaplot.R': No such file or directory
Traceback (most recent call last):
  File "/home/juaguila/MethylC-analyzer/scripts/MethylC.py", line 849, in <module>
    Delta_Meta('CG')
  File "/home/juaguila/MethylC-analyzer/scripts/MethylC.py", line 309, in Delta_Meta
    exp_df.append(pd.read_csv(path_to_files+expfile+"_"+ context +".matrix.gz" ,sep='\t', skiprows=1,compression ='gzip',na_values='-',header =None))
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/juaguila/.conda/envs/methylC/lib/python3.9/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

------

Why is it failing ?
I am using the full path of the directory since it complains and required that - which is not mentioned in the tutorial, not even the "all" argument.

I am worried because I have big files, about 400Mb each, and I have 44 of them, and I want the software to run properly. 


Hope this error can be fixed.
